# Fast experimental configuration for parameter sweeping
model_name: "transformer_fast_experiment"

# Data parameters - REDUCED FOR SPEED
data_dir: "../selected_h5/"
num_files: 3          # Only 5 files instead of 50
max_cells: 30         # Reduced from 50
min_cells: 3
cell_selection_feature: "Cell_e"
use_spatial_features: true

# Cell filtering parameters
use_cell_track_matching: true
require_valid_cells: true
additional_cell_filters: {}

# Data split parameters
test_size: 0.3
val_split: 0.33333
random_state: 42

# Model architecture parameters - Same as original
d_model: 64
num_heads: 4
dff: 128
num_transformer_blocks: 3
dropout_rate: 0.1

# Dense layer parameters
vertex_dense_units: 8
final_dense_units: [32, 16, 8]
final_dropout_rates: [0.2, 0.1, 0.1]
use_batch_norm: true

# Training parameters - REDUCED FOR SPEED
batch_size: 32        # Smaller batch size
epochs: 5            # Much fewer epochs (was 30)
learning_rate: 0.0001  # Slightly higher for faster convergence
lr_reduction_factor: 0.5
early_stopping_patience: 5    # Reduced from 10
lr_patience: 3        # Reduced from 5
min_lr: 0.0000001

# Model save parameters
models_base_dir: "models"

# Feature definitions - Same as original
spatial_features: ["Cell_x", "Cell_y", "Cell_z"]
vertex_spatial_features: ["HSvertex_reco_x", "HSvertex_reco_y", "HSvertex_reco_z"]
all_cell_features:
  - "Cell_x"
  - "Cell_y"
  - "Cell_z"
  - "Cell_eta"
  - "Cell_phi"
  - "Cell_Barrel"
  - "Cell_layer"
  - "Cell_time_TOF_corrected"
  - "Cell_e"
  - "Cell_significance"
  - "matched_track_pt"
  - "matched_track_deltaR"
skip_normalization: ["Cell_time_TOF_corrected", "Cell_Barrel", "Cell_layer"]